# Generated by Django 4.0.1 on 2022-01-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_show'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('key', 'value')},
        ),
    ]
