# Generated by Django 4.0.1 on 2022-01-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
