# Generated by Django 4.0.1 on 2022-01-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('key', 'value')},
        ),
    ]
