# Generated by Django 4.0.1 on 2022-01-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profile_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
    ]
